name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Starting
    - name: Run a multi-line script
      run: |
        chmod +x build.sh
        ./build.sh
